openapi: '3.0.2'
info:
  title: 'Dummies'
  description: 'Dummies REST API'
  version: '1'
paths:
  /dummies:
    get:
      tags:
        - dummies
      operationId: 'get_dummies'
      parameters:
      - name: trace_id
        in: query
        description: Trace ID
        required: false
        schema:
          type: string
      - name: key
        in: query
        description: Key of dummy object
        required: false
        schema:
          type: string
      - name: skip
        in: query
        description: Number of objects to skip
        required: false
        schema:
          type: integer
      - name: take
        in: query
        description: Number of objects to return a a page
        required: false
        schema:
          type: integer
      - name: total
        in: query
        description: Total number of objects
        required: false
        schema:
          type: boolean
      responses:
        200:
          description: 'Successful response'
          content:
            application/json:
              schema:
                type: 'object'
    post:
      tags:
        - dummies
      operationId: 'create_dummy'
      parameters:
      - name: trace_id
        in: query
        description: Trace ID
        required: false
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              properties:
                id:
                  type: 'string'
                key:
                  type: 'string'
                content:
                  type: 'string'
              required:
                - key
      responses:
        201:
          description: 'Successful response'
          content:
            application/json:
              schema:
                type: 'object'
  /dummies/{dummy_id}:
    get:
      tags:
        - dummies
      operationId: 'get_dummy_by_id'
      parameters:
      - name: dummy_id
        in: path
        description: ID of dummy object
        required: true
        schema:
          type: string
      - name: trace_id
        in: query
        description: Trace ID
        required: false
        schema:
          type: string
      responses:
        200:
          description: 'Successful response'
          content:
            application/json:
              schema:
                type: 'object'
    put:
      tags:
        - dummies
      operationId: 'update_dummy'
      parameters:
      - name: dummy_id
        in: path
        description: ID of dummy object
        required: true
        schema:
          type: string
      - name: trace_id
        in: query
        description: Trace ID
        required: false
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              properties:
                id:
                  type: 'string'
                key:
                  type: 'string'
                content:
                  type: 'string'
              required:
                - key
      responses:
        200:
          description: 'Successful response'
          content:
            application/json:
              schema:
                type: 'object'
    delete:
      tags:
        - dummies
      operationId: 'delete_dummy'
      parameters:
      - name: dummy_id
        in: path
        description: ID of dummy object
        required: true
        schema:
          type: string
      - name: trace_id
        in: query
        description: Trace ID
        required: false
        schema:
          type: string
      responses:
        200:
          description: 'Successful response'
          content:
            application/json:
              schema:
                type: 'object'
