FROM golang:1.20

# Set environment variables for Go
ENV GO111MODULE=on \
CGO_ENABLED=1 \
GOOS=linux

# Set a working directory
WORKDIR /app

# Copy the entire project
COPY . .

# Install all go_modules
RUN go mod tidy
RUN go mod download

# Specify the command from running tests
CMD go test -v -tags sqlite_json ./test/...
