version: '3.3'

services:
  test:
    build:
      context: ..
      dockerfile: docker/Dockerfile.test
    image: ${IMAGE:-pipdevs/test}
    depends_on:
      - redis
    environment:
      - REDIS_SERVICE_HOST=redis
      - REDIS_SERVICE_PORT=6379

  redis:
    image: redis:latest
    # container_name: redis
    # ports:
    #   - "6379:6379"