version: '3.3'

services:

  rabbitmq:
    image: rabbitmq:3.8.9-alpine
    environment: 
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password
    # container_name: rabbitmq
    ports:
      - "5672:5672"