version: '3.3'

services:

  zookeeper:
    image: zookeeper
    ports:
      - 2181:2181
    environment:
      - ZOO_MY_ID=1
      - ZOO_PORT=2181
      - ZOOKEEPER_SERVERS=server.1=zookeeper:2888:3888
      - ZOOKEEPER_SASL_ENABLED="false"

  kafka:
    image: confluentinc/cp-kafka:5.1.0
    ports:
      - "9092:9092"
    environment:
      - KAFKA_LISTENERS=PLAINTEXT://:9092
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9092
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - ZOOKEEPER_SASL_ENABLED=false
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
    depends_on:
      - zookeeper