package validate

// ValidationResultType types of validation results generated by validation schemas.
//	Information = 0 General information (not an error).
//	Warning = 1 Warning about something suspecious. In strict mode is treated as error
//	Error = 2 - Validation error.
type ValidationResultType int

const (
	Information ValidationResultType = iota
	Warning
	Error
)
