# Build stage
FROM golang:1.20

# set working directory
WORKDIR /app

COPY . .

# Install Protoc
RUN apt-get update && apt-get install -y protobuf-compiler

# Install go plugins
RUN go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@latest
RUN go install google.golang.org/protobuf/cmd/protoc-gen-go@latest

# Generate
RUN protoc --go_out=. --go_opt=paths=source_relative --go-grpc_out=. --go-grpc_opt=paths=source_relative protos/commandable.proto
RUN protoc --go_out=. --go_opt=paths=source_relative --go-grpc_out=. --go-grpc_opt=paths=source_relative test/protos/dummies.proto