---
- descriptor: "pip-services:logger:console:default:1.0"
  level: "trace"

# In service mode uncomment one of next dependencies
- descriptor: "pip-services-dummies:service:awslambda:default:1.0"
#- descriptor: "pip-services-dummies:service:commandable-awslambda:1.0"
